### ISSUE TITLE
AnyOf not holding information / not saving

### ISSUE THREAD

**Issue by BeOurGuest-Discord** [AngryBeaver/beavers-crafting#145] opened 2024-08-24 19:53 UTC
**System:** A5e

**Modules/System Versions:**
A5e version 0.19.24
Beaver's Crafting Module 3.6.1

When creating an Anyof item(object?), I'm experiencing multiple issues that I'm hoping are all related. 

_Issue 1:_ Any code put into the code box  will go away upon closing the item page, or hitting the test item button. The code is removed when hitting the Test Item button even when an item is on the sheet, and nothing appears to happen. 

_Issue 2:_ If the Anyof item page has been closed and then is reopened, items can not be dragged into the page. They can be dragged into the page if you do it right after creating the Anyof Item before closing it.

_Issue 3:_ Items dragged into the Anyof Item will persist and remain on the page after using the test item button, and can not be removed in any way. Hitting the red x on the sheet does not remove the item.  This occurs whether you have closed the item window or not.

**Comment by AngryBeaver** [comment] 2024-08-25 06:39
i will have a look.

**Comment by AngryBeaver** [comment] 2024-08-25 07:56
thx for creating this bugticket i do not play most of the systems my module is compatible with. 
This apear to only break on A5e also the system seems to run on top of svelte and i have no clue why it breaks or work at all :-). 

Anyhow i made some adaptions for anyOf  ( usually i asume a FormApplication as base class for the item now i am more independent of it and it seems to work with a5e and other systems so far)

issue 1 and 2 are fixed with 3.6.2. Issue 3 is not a bug in my opinion you can still drop another item on top and so you already have an item you can test your macro with.


Also i could not see any major diffrencies between anyOf and recipeSheet and the later seems to work... ( i have currently no clue that is not great )

**Comment by AngryBeaver** [comment] 2024-08-25 08:10
plz confirm and close this ticket when it do work for issue 1 + 2.

**Closed** 2024-08-25 12:08 UTC

**Comment by AngryBeaver** [comment] 2024-08-31 22:18
4.0.3 should fix some issues with recipe sheet i encountered on a5e
